cache:
   pipeline: ["~/.m2"]

annotations:
   screwdriver.cd/restrictPR: fork

shared:
   annotations:
       screwdriver.cd/cpu: TURBO
       screwdriver.cd/ram: TURBO

   environment:
       #Fetches history so Sonar can assign blame.
       GIT_SHALLOW_CLONE: false
       CONTAINER: "open-jdk11-latest"
       JDK_VERSION: "11"
       ENABLE_MAVEN_OWASP_CHECK: "true"
   secrets:
       - GSHEET_JDBC_CREDENTIALS
       - COVERALLS_REPO_TOKEN


jobs:
  master-commit:
    image: maven:3.8.2-openjdk-11
    requires: [~pr, ~commit]
    steps:
      - build: mvn -B clean verify coveralls:report -PallTests

  release-java11:
    image: maven:3.8.2-openjdk-11
    secrets:
        - GPG_KEYNAME
        - GPG_PASSPHRASE
        - GPG_ENCPHRASE
        - OSSRH_USER
        - OSSRH_TOKEN
    requires: [~tag, ~release]
    steps:
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"
